config/routes.rb
Rails.application.routes.draw do

    #static routes
  root to: 'static#home'
  
  resources :posts 
  resources :dcds do 
    resources :posts, only: [:new, :create, :index, :show] do 
      resources :comments 
    end
  end #gives all the restful routes
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  get '/sign_out', to: 'devise/sessions#destroy'
  get '/mine', to: 'dcds#mine'
  
  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post

  validates_length_of :content, minimum: 1, maximum: 100, allow_blank: false
end

app/models/dcd.rb
class Dcd < ApplicationRecord
  

  validates :first_name, presence: :true 
  validates :last_name, presence: :true
  validates :relationship, presence: true
  validates :birthday, presence: true
  validates :deathday, presence: true
  validates :gender, presence: true


  belongs_to :user
  has_many :posts, dependent: :delete_all
  has_one_attached :picture


  # @search = params["search"]
  #   if @search.present?
  #     @first_name = @search["first_name"]
  #     @dcds = Dcd.where("first_name LIKE ?", "%#{@first_name}%")
  #   end

  # def self.search_dcd(name)
  #   where("first_name, last_name LIKE ?", "%#{name}%")
  # end 


  def full_name
    "#{self.first_name} #{self.last_name}"
  end

  def self.search(params)
    where("LOWER(first_name) || ' ' || LOWER(last_name) LIKE :s", :s => "%#{params.downcase}%")
  end #downcase attributes ,, checking both i guess, stage parameter assigning to key of S our params downcased -- looking for similarities. 
end

app/models/post.rb
class Post < ApplicationRecord
  

  belongs_to :user
  belongs_to :dcd, dependent: :delete
  has_many :comments
  has_one_attached :picture


  validates_length_of :post_content, minimum: 1, maximum: 100, allow_blank: false
  validates :title, presence: true 

  accepts_nested_attributes_for :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  devise :omniauthable, :omniauth_providers => [:facebook]       

  has_many :posts
  has_many :dcds
  has_many :comments, through: :posts
  has_many :posts, through: :dcds
  

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name   # assuming the user model has a name
      user.image = auth.info.image # assuming the user model has an image
    end
  end  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  

  # def find_post(post)
  #   @post = Post.find_by_id(post) #creating dynamic method works between multiple controllers -- pass in params within this method and does the query for me 
  # end

  def find_dcd
    @dcd = Dcd.find_by_id(params[:dcd_id])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
before_action :find_dcd
before_action :find_post
before_action :find_comments, only: [:edit, :update, :destroy]
before_action :redirect_if_not_dcd_user, only: [:edit, :update, :destroy]
before_action :redirect_if_no_comment, only: [:update, :destroy]

  def index
    @comments = Comment.all
  end

  def new
   
  end

  def create
    @comment = Comment.new(comment_params)
      @post = @comment.post
      if @comment.save
        redirect_to dcd_post_path(@dcd, @post)
      else
        flash.now[:error] = @comment.errors.full_messages
        render :'posts/show'
      end
    end 
    
    def edit
      redirect_if_not_dcd_user
    end
    
  def update
    @comment.update(comment_params)
    redirect_if_not_dcd_user
    if @comment.save
      redirect_to dcd_post_path(@dcd, @post)
    else
      flash.now[:error] = @comment.errors.full_messages
      render :edit
    end
  end
  
  def destroy
    @comment.destroy
    redirect_to dcd_post_path(@dcd, @post)
  end
  
  private
  
  def comment_params
    params.require(:comment).permit(:content, :user_id, :post_id, comments_attributes: [:user_id, :post_id, :content])
  end
  
  def find_comments
    @comment = Comment.find_by_id(params[:id])
  end
  
  def redirect_if_not_dcd_user
    redirect_to dcd_posts_path unless current_user.id == @comment.user_id 
  end
  
  def find_post
    @post = Post.find_by_id(params[:post_id])
  end

  def redirect_if_no_comment
    # binding.pry
    redirect_to dcd_post_path(@post) unless @comment 
  end 
end

app/controllers/dcds_controller.rb
class DcdsController < ApplicationController
  before_action :find_dcds, only: [:show, :edit, :destroy, :update, :search]
  
  
#dcd = Deceased

  def index 
    @dcds = Dcd.all
    if params[:query]
      @dcds = @dcds.search(params[:query])
    end
  end

  def mine 
    @dcds = Dcd.all
    @dcds = current_user.dcds
  end 

  def show
  end 

  def new
    if @post 
      render :new_dcd_post
     else
       @dcd = Dcd.new 
     end
  end

  def create
    @dcd = Dcd.new(dcd_params)
      if @dcd.save
        redirect_to dcds_path  
      else 
        error
        render :new
    end
  end 

  def edit
   redirect_if_not_dcd_user
  end 

  def update
    if @dcd.update(dcd_params)
      redirect_to dcd_path(@dcd)
    else
      error
      render :edit
    end
  end 

  def destroy 
    redirect_if_not_dcd_user
    @dcd.destroy
    flash[:notice] = "#{@dcd.full_name} was successfully removed."
    redirect_to dcds_path
  end

  private

  def find_dcds
    @dcd = Dcd.find_by_id(params[:id])
  end 

  def dcd_params #permit only the attributes we added to our object
    params.require(:dcd).permit(:first_name, :last_name, :relationship, :gender, :birthday, :deathday, :bio, :picture, :search, :user_id)
  end 
  
  def error
    flash.now[:error] = @dcd.errors.full_messages
  end

  def redirect_if_not_dcd_user
    redirect_to dcd_path(@dcd) unless current_user.id == @dcd.user_id
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_dcd, only: [:new, :show]
  before_action :find_post, only: [:new, :create, :show]
  before_action :redirect_if_no_post, only: [:show]

  def show
    @comment = Comment.new
    # binding.pry
  end

  def index
    @posts = Post.all
  end
    
  def new
    # binding.pry
    @post = Post.new 
    render :new_dcd_post
  end
  
  def create
    @dcd = Dcd.find_by(params[:dcd_id])
    @post = Post.new(post_params)
    # binding.pry
    if @post.save
      # binding.pry
      redirect_to dcd_post_path(@dcd, @post)
    else
      flash.now[:error] = @post.errors.full_messages
      render :new_dcd_post
    end
  end
  
  
  private 
  
  def post_params
    params.require(:post).permit(:title, :post_content, :user_id, :dcd_id, :picture)
  end
  
  def redirect_if_no_post
    # binding.pry
    redirect_to dcd_posts_path unless @post
  end 

  def find_post
    @post = Post.find_by_id(params[:id])
  end 

end

app/controllers/static_controller.rb
class StaticController < ApplicationController

    def home

    end 
end 

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])
   
    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/dcds_helper.rb
module DcdsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/edit.html.erb
<%= form_for [@dcd, @post, @comment] do |f| %>
  
  <%= f.label :content %> <br>
  <%= f.text_area :content %>
  <br>
  
  
  <%= f.submit %>
<% end %>
<br><br>

app/views/dcds/_form.html.erb
  <div class = "containter">
<%= form_for dcd do |f| %> 
  <%= f.hidden_field :user_id, :value => current_user.id %>
<div class="row">   
  <div class="col s6"> 
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div class="col s6"> 
    <%= f.label :last_name %>
    <%= f.text_field :last_name %> 
  </div> 
</div>
<div class="row">
 <div class="col s6">
    <%= f.label :gender %>
    <%= f.text_field :gender %> 
  </div> 
  <div class="col s6">
    <%= f.label :relationship %>
    <%= f.text_field :relationship %> 
  </div> 
</div>
  <div>
    <%= f.label :birthday %>
    <%= f.date_field :birthday%> 
  </div> 
  <div>
    <%= f.label :deathday %>
    <%= f.date_field :deathday %> 
  </div> 
  <div>
    <%= f.label :bio %>
    <%= f.text_field :bio %> 
  </div> 
  <div class="field">
    <%= f.label :picture %>
    <%= f.file_field :picture %>
  </div>

  <%= f.submit button_name %> 
<% end %> 


<script> $(document).ready(function(){
    $('.datepicker').datepicker();
  });</script>

app/views/dcds/edit.html.erb
<h4>Edit <%= @dcd.first_name %> <%= @dcd.last_name %></h4>

<%= render partial: "form", locals: { dcd: @dcd, button_name: "Edit"} %>

app/views/dcds/index.html.erb
<center><h1>Who to celebrate today? </h1>

<div class="container">
  <div class="row">
      <div class="col s6 m6">
        <% @dcds.each do |dcd| %> 
          <div class="card">
            <div class="card-image">
              <%= image_tag(dcd.picture, width: 200) if dcd.picture.attached? %>
            </div>
            <div class="card-action">
            <%= link_to dcd.full_name, dcd_path(dcd)=%>
          </div>
          </div>
        <% end %> 
      </div>
    </div>
  </div> 
</center>

app/views/dcds/mine.html.erb
<h1>Test</h1>

<div class="container">
  <div class="row">
      <div class="col s6 m6">
        <% @dcds.each do |dcd| %> 
          <div class="card">
            <div class="card-image">
              <%= image_tag(dcd.picture, width: 200) if dcd.picture.attached? %>
            </div>
            <div class="card-action">
            <%= link_to dcd.full_name, dcd_path(dcd)=%>
          </div>
          </div>
        <% end %> 
      </div>
    </div>
  </div> 

app/views/dcds/new.html.erb
<h1>Unearth your loved one.</h1>

<%= render partial: "form", locals: { dcd: @dcd, button_name: "Add"} %>
 

app/views/dcds/show.html.erb
<center>

  <h1><%= @dcd.full_name %> </h1>

<div class="container">
  <div class="row">
    <div class="card">
      <div class="card-image waves-effect waves-block waves-light">
      <%= image_tag(@dcd.picture, width: 100) if @dcd.picture.attached? %> 
    </div>
    <div class="card-content">
      <span class="card-title activator grey-text text-darken-4">Click to Read More About <%= @dcd.full_name %><i class="material-icons right">more_vert</i></span>
      <% if @dcd.user == current_user %>
        <%= link_to "Edit", edit_dcd_path(@dcd) %> &nbsp; &nbsp; <%= link_to "Remove", dcd_path(@dcd), method: "delete" %>
      <% end %>
    </div>
    <div class="card-reveal">
      <span class="card-title grey-text text-darken-4">Information<i class="material-icons right">close</i></span>
        <p>Relationship: <%= @dcd.relationship %></p> 
        <p>Gender: <%= @dcd.gender %></p>
        <p>Birthday: <%= @dcd.birthday %></p>
        <p>Death Day: <%= @dcd.deathday %></p>
        <p>Bio: <%= @dcd.bio %></p>
      </div>
    </div>
  </div>
</div>

<h4>Share Your Memories!</h4>
</center>
<% if @dcd.posts %>
  <% @dcd.posts.each do |p| %>
  <div>
    <h2><%= p.title %></h2>
    <%= image_tag(p.picture, width: 200) if p.picture.attached? %>
    <p><%= p.post_content %></p>
  <%= link_to "See Post", dcd_post_path(@dcd, p) %><br><br>
  </div>
  <% end %>
<% end %>

<%= link_to "Add a Post", new_dcd_post_path(@dcd) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RIPNote</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
            
  </head>

  <body>
    <nav>
    <div class="nav-wrapper grey darken-1">
      <a href="/" class="center brand-logo">RiPNote</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <li><%= link_to("Home", root_path) %></li>
          <% unless current_user %>
        <li><%= link_to "Sign in with Facebook", user_facebook_omniauth_authorize_path, method: :post %></li>
        <li><%= link_to("Log In", user_session_path) %></li>
        <li><%= link_to("Sign Up", new_user_registration_path) %></li>
            <% else %> 
        <li><%= link_to("My Deceased", mine_path) %></li>   
        <li><%= link_to("Deceased", dcds_path) %></li>
        <li><%= link_to("Add A Deceased", new_dcd_path) %></li>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
    
        <% end %> 
      </ul>
    </nav>
    <% if flash[:error] %>
      <% flash[:error].each do |error| %>
        <p><%= error %></p>
      <% end %> 
    <% end %>

    <%= content_tag("p", flash[:notice]) if flash[:notice] %>
     <div class="container">
    <%= yield %>
  </body>
</html>


 <script> $(document).ready(function(){
    $('.materialboxed').materialbox();
  });
        </script>

app/views/posts/index.html.erb
<% @posts.each do |p| %>
  <h2><%= p.title %></h2>
  <p><%= p.post_content %></p>
<% end %>

app/views/posts/new_dcd_post.html.erb
<h1>Post on Someones Page!</h1>

   <%= form_for(@post) do |f| %> <!--  -->
    <%= f.hidden_field :user_id, value: current_user.id %> <!-- method from devise to call the user -->
      <%= f.hidden_field :dcd_id, value: @dcd.id %> <!-- calling it from the instance variable in the form --> 
      <%= f.label :title %>
      <%= f.text_field :title %>

      <%= f.label :post_content %>
      <%= f.text_field :post_content %>
      <div class="field">
        <%= f.label :picture %>
        <%= f.file_field :picture %>
      </div>

      <%= f.submit %>

  <% end %> 

app/views/posts/show.html.erb
<h1><%= @post.title %></h1>
<%= image_tag(@post.picture, width: 200) if @post.picture.attached? %>
<p><%= @post.post_content %></p>

<%= form_for [@dcd, @post, @comment] do |f| %>
  <%= f.hidden_field :user_id, value: current_user.id %> 
  <%= f.hidden_field :post_id, value: @post.id %>
  <%= f.label :content %><br>
  <%= f.text_area :content %><br>

  <%= f.submit %> 
<% end %>

<h3>Comments</h3>
<% if @post.comments %>
  <% @post.comments.each do |c|%>
   <% if c.id != nil %> <!-- saying  --> 
    <%= "#{c.user.email} said: #{c.content}" %>
    <% if current_user.id == c.user_id %>
        <%= link_to "Edit", edit_dcd_post_comment_path(@dcd, @post, c)%>
        <%= link_to "Delete", dcd_post_comment_path(@dcd, @post, c), method: 'delete' %>
      <% end %>

      <br> <br>
    <% end %> 
  <% end %> 
<% end %> 